version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11.1.0
    steps:
      - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: npm-install
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
